name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Build and run services with Docker Compose
        run: |
          docker-compose -f deployment/docker-compose.yml up --build -d

      - name: Run tests
        run: |
          docker-compose -f deployment/docker-compose.yml run test-runner

      - name: Tear down services
        if: always()
        run: |
          docker-compose -f deployment/docker-compose.yml down

  cleanup:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Remove dangling Docker containers/images
        run: |
          docker container prune -f
          docker image prune -f
